"""
Workana applier — Playwright + saved cookies.

Workana apply flow:
  1. Navigate to project/job URL
  2. Click "Enviar propuesta"
  3. Fill proposal form (description, bid amount)
  4. Submit

The proposal description is generated by the LLM via FormFiller.
"""
from pathlib import Path
from typing import Optional

import structlog
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
from playwright_stealth import stealth_sync

from ai_engine.cv_loader import get_cv
from ai_engine.form_filler import FormFiller, OrphanQuestion
from core.models import Application, Job
from core.enums import ApplicationStatus
from core.playwright_config import CHROMIUM_ARGS, headless
from services.applier import ApplicationResult, AuthExpired, BaseApplier, CaptchaDetected, register
from services.screenshot import capture

logger = structlog.get_logger()

BASE_URL = "https://www.workana.com"
APPLY_BTN_SELECTOR = (
    "a.btn-apply, button.btn-apply, "
    "a:has-text('Envía una propuesta'), "
    "a:has-text('Enviar propuesta'), "
    "button:has-text('Enviar propuesta'), "
    "a.btn-primary:has-text('propuesta')"
)
SUCCESS_SELECTOR = ".proposal-sent, [class*='proposal-sent'], h2:has-text('propuesta enviada')"
AUTH_SELECTOR = "a[href*='/login'], .login-modal"
CLOSED_SELECTOR = "h1:has-text('[Cerrado]'), h1:has-text('[Closed]')"
ACTIVATION_MODAL_BTN = (
    "button:has-text('Continuar enviando'), "
    "a:has-text('Continuar enviando'), "
    ".modal .btn-primary:visible, "
    ".modal-content .btn-primary:visible"
)


@register
class WorkanaApplier(BaseApplier):
    platform_name = "workana"
    cv_profile_name = "remoto"

    def _do_apply(self, application: Application, job: Job) -> ApplicationResult:
        if not self.session_manager.has_cookies("workana"):
            raise AuthExpired("No cookies for workana")

        resume_step = self._get_resume_step(application)
        filler = FormFiller(self.cv_profile_name)
        cv_data = get_cv(self.cv_profile_name)

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=headless(), args=CHROMIUM_ARGS)
            context = browser.new_context(
                locale="es-AR",
                viewport={"width": 1280, "height": 900},
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/124.0.0.0 Safari/537.36"
                ),
            )
            self.session_manager.inject_into_playwright(context, "workana")
            page = context.new_page()
            stealth_sync(page)

            try:
                if resume_step <= 0:
                    self._save_checkpoint(application, 0, "navigate")
                    page.goto(job.url, wait_until="domcontentloaded", timeout=30_000)
                    if page.locator(AUTH_SELECTOR).count() > 0:
                        raise AuthExpired("Workana session expired")
                    if page.locator(CLOSED_SELECTOR).count() > 0:
                        browser.close()
                        return ApplicationResult(
                            False, ApplicationStatus.FAILED.value, "Project is closed"
                        )

                if resume_step <= 1:
                    self._save_checkpoint(application, 1, "click_apply")
                    try:
                        page.locator(APPLY_BTN_SELECTOR).first.click(timeout=8_000)
                    except PWTimeout:
                        screenshot = capture(page, f"no_apply_btn_{job.id}")
                        browser.close()
                        return ApplicationResult(
                            False, ApplicationStatus.FAILED.value,
                            "Apply button not found", screenshot_path=screenshot,
                        )
                    # Wait for proposal form (textarea) to become visible
                    try:
                        page.wait_for_selector(
                            "textarea[name*='proposal'], textarea[name*='description'], textarea:visible",
                            timeout=10_000,
                        )
                    except PWTimeout:
                        screenshot = capture(page, f"no_proposal_form_{job.id}")
                        browser.close()
                        return ApplicationResult(
                            False, ApplicationStatus.FAILED.value,
                            "Proposal form did not open", screenshot_path=screenshot,
                        )

                if resume_step <= 2:
                    self._save_checkpoint(application, 2, "fill_proposal")
                    orphans = _fill_proposal(page, filler, cv_data, job)
                else:
                    orphans = []

                if resume_step <= 3:
                    self._save_checkpoint(application, 3, "submit")
                    if orphans:
                        browser.close()
                        return ApplicationResult(
                            False, ApplicationStatus.REVIEW_FORM.value,
                            orphan_questions=orphans,
                        )
                    _submit(page, job.id)

                if resume_step <= 4:
                    self._save_checkpoint(application, 4, "verify")
                    try:
                        page.wait_for_selector(SUCCESS_SELECTOR, timeout=10_000)
                    except PWTimeout:
                        screenshot = capture(page, f"unconfirmed_workana_{job.id}")
                        browser.close()
                        return ApplicationResult(
                            False, ApplicationStatus.FAILED.value,
                            "Could not confirm proposal submission", screenshot_path=screenshot,
                        )

                browser.close()
                return ApplicationResult(True, ApplicationStatus.APPLIED.value)

            except (CaptchaDetected, AuthExpired):
                browser.close()
                raise
            except Exception as e:
                screenshot = capture(page, f"error_workana_{job.id}")
                browser.close()
                return ApplicationResult(False, ApplicationStatus.FAILED.value, str(e), screenshot_path=screenshot)


def _fill_proposal(page, filler: FormFiller, cv_data: dict, job: Job) -> list[dict]:
    orphans = []

    # Proposal/cover letter textarea
    proposal_inputs = page.locator("textarea[name*='proposal'], textarea[name*='description'], textarea:visible")
    if proposal_inputs.count() > 0:
        try:
            # Use cover letter from CV or generate via LLM
            cover = cv_data.get("cover_letter") or filler.fill("carta de presentación para propuesta freelance", required=True)
            if cover:
                proposal_inputs.first.fill(cover[:1500])
        except OrphanQuestion as oq:
            orphans.append({"field": oq.question_text, "required": True})

    # Bid amount — use salary expectation from answers.yaml
    bid_input = page.locator("input[name*='budget'], input[name*='bid'], input[name*='amount']")
    if bid_input.count() > 0 and not bid_input.first.input_value():
        try:
            answer = filler.fill("bid_amount_usd", field_type="number", required=False)
            if answer:
                bid_input.first.fill(answer)
        except OrphanQuestion:
            pass

    return orphans


def _submit(page, job_id: int):
    try:
        btn = page.locator(
            "button[type='submit']:visible, button:has-text('Enviar'):visible, "
            "button:has-text('Send proposal'):visible"
        ).first
        btn.click(timeout=8_000)
        page.wait_for_load_state("domcontentloaded", timeout=20_000)
        logger.info("workana.submitted", job_id=job_id)
    except PWTimeout as e:
        raise Exception(f"Submit failed: {e}")
